### ISSUE TITLE
Lab08 - new mlflow version leads to error

### ISSUE THREAD

**Issue by johnnyDEDK** [MicrosoftLearning/mslearn-azure-ml#10]
# Module: Use MLflow to track training jobs
#### Step: 01

Description of issue
with mlflow version >= 2.1.1

```
import mlflow
experiments = mlflow.list_experiments()
for exp in experiments:
    print(exp.name)
```
leads to 
`AttributeError: module 'mlflow' has no attribute 'list_experiments'`

Repro steps:

1. Follow https://microsoftlearning.github.io/mslearn-azure-ml/Instructions/08-Script-mlflow-tracking.html

#### Fix:
```
from mlflow.tracking import MlflowClient

client = MlflowClient()
experiments = (
    client.search_experiments()
)
for exp in experiments:
    print(exp.name)
```

**Comment by madiepev** [comment]
The instructions are designed to work with the Python 3.8 - Azure ML kernel. Did you use that kernel? Did you independently update mlflow? Or did you run the notebook somewhere else?

**Comment by Jason-Microsoft-MTT** [comment]
I am just echoing the issue - according to the updated documentation https://learn.microsoft.com/en-us/azure/machine-learning/how-to-track-experiments-mlflow?view=azureml-api-2#getting-all-the-experiments - the list_experiments() doesn't work after version 2.0 which I assume is what is installed on the kernel. Needs updated to search_experiments()
